name: esp32 port

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'shared/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/esp32/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_idf50:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: source tools/ci.sh && ci_esp32_idf50_setup
    - name: Build
      run: source tools/ci.sh && ci_esp32_build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
        name: artifact # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/runner/work/micropython-1/micropython-1/ports/esp32/build-ESP32_GENERIC_S3
        # The desired behavior if no files are found using the provided path.
